language: objective-c
osx_image: xcode7.2

before_install:
  - bash installcarthage 0.12

install: carthage bootstrap --platform iOS --no-use-binaries --verbose

script:
  - xcodebuild -project Search.xcodeproj -scheme Search test
